/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import java.awt.Image;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import model.Employee;
import model.EmployeeHistory;

/**
 *
 * @author nihar
 */
public class ViewJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewJPanel
     */
    EmployeeHistory empHistory;
    public ViewJPanel(EmployeeHistory empHistory) {
        initComponents();
        this.empHistory = empHistory;
        
        populateTable();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTxtEmail = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTxtCellPhoneNum = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTxtTeamInfo1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jTxtName = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jTxtEmpID = new javax.swing.JTextField();
        jTxtAge = new javax.swing.JTextField();
        jTxtLevel = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblEmployees = new javax.swing.JTable();
        userPic = new javax.swing.JLabel();
        jBtnView = new javax.swing.JButton();
        jBtnDelete = new javax.swing.JButton();
        jBtnUpdate = new javax.swing.JButton();
        jTxtSearchName = new javax.swing.JTextField();
        jTxtSearchId = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jTxtStartDate = new javax.swing.JTextField();
        jTxtGender = new javax.swing.JTextField();
        jTxtPositionTitle1 = new javax.swing.JTextField();

        jLabel1.setText("Name");

        jLabel2.setText("Employee ID");

        jTxtCellPhoneNum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtCellPhoneNumActionPerformed(evt);
            }
        });
        jTxtCellPhoneNum.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTxtCellPhoneNumKeyPressed(evt);
            }
        });

        jLabel3.setText("Age");

        jLabel4.setText("Gender");

        jLabel5.setText("Start Date");

        jLabel6.setText("Level");

        jLabel7.setText("Team Info");

        jLabel8.setText("Position Title");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel9.setText("Contact Info");

        jLabel10.setText("Cell Phone");

        jLabel11.setText("Email Address");

        jTxtEmpID.setEnabled(false);
        jTxtEmpID.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTxtEmpIDKeyPressed(evt);
            }
        });

        jTxtAge.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTxtAgeKeyPressed(evt);
            }
        });

        tblEmployees.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Emp Id", "Title", "Level"
            }
        ));
        tblEmployees.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblEmployeesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblEmployees);

        jBtnView.setText("View");
        jBtnView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnViewActionPerformed(evt);
            }
        });

        jBtnDelete.setText("Delete");
        jBtnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnDeleteActionPerformed(evt);
            }
        });

        jBtnUpdate.setText("Update");
        jBtnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnUpdateActionPerformed(evt);
            }
        });

        jTxtSearchName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtSearchNameActionPerformed(evt);
            }
        });
        jTxtSearchName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTxtSearchNameKeyReleased(evt);
            }
        });

        jTxtSearchId.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTxtSearchIdKeyReleased(evt);
            }
        });

        jLabel12.setText("Search by Name");

        jLabel13.setText("Search by Emp Id");

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("Employee Data");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel4)
                                            .addComponent(jLabel3)
                                            .addComponent(jLabel2)
                                            .addComponent(jLabel1)
                                            .addComponent(jLabel10))
                                        .addGap(39, 39, 39)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(jTxtName, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jTxtEmpID, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jTxtAge, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jTxtCellPhoneNum, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jTxtGender, javax.swing.GroupLayout.Alignment.LEADING)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGap(105, 105, 105)
                                        .addComponent(userPic, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                .addGap(128, 128, 128)
                                                .addComponent(jLabel6))
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                .addGap(102, 102, 102)
                                                .addComponent(jLabel5))
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                .addGap(83, 83, 83)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING))))
                                        .addGap(26, 26, 26)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jTxtLevel)
                                            .addComponent(jTxtTeamInfo1)
                                            .addComponent(jTxtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jTxtStartDate, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jTxtPositionTitle1)))))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel12)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jTxtSearchName, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(29, 29, 29)
                                    .addComponent(jLabel13)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jTxtSearchId, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 666, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jBtnView)
                                .addGap(32, 32, 32)
                                .addComponent(jBtnDelete))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(403, 403, 403)
                        .addComponent(jBtnUpdate)))
                .addContainerGap(154, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel14)
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTxtSearchName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtSearchId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13))
                .addGap(45, 45, 45)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jBtnView)
                            .addComponent(jBtnDelete)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(userPic, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jTxtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jTxtEmpID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jTxtAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jTxtGender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(92, 92, 92)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(jTxtCellPhoneNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jTxtStartDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jTxtLevel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jTxtTeamInfo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(jTxtPositionTitle1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(53, 53, 53)
                        .addComponent(jLabel9)
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(jTxtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(43, 43, 43)
                .addComponent(jBtnUpdate)
                .addContainerGap(51, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnDeleteActionPerformed
       int selectedRowIndex = tblEmployees.getSelectedRow();
       if(selectedRowIndex<0){
           JOptionPane.showMessageDialog(this, "Please select a row to delete");
           return;
       };
       DefaultTableModel model = (DefaultTableModel) tblEmployees.getModel();
       Employee selectedEmp = (Employee)model.getValueAt(selectedRowIndex, 0);
       
       empHistory.deleteEmployee(selectedEmp);
       JOptionPane.showMessageDialog(this, "Employee deleted");
       populateTable();
       selectedEmp = null;
    }//GEN-LAST:event_jBtnDeleteActionPerformed

    private void jBtnViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnViewActionPerformed
        int selectedRowIndex = tblEmployees.getSelectedRow();
       if(selectedRowIndex<0){
           JOptionPane.showMessageDialog(this, "Please select a row to view");
           return;
       };
       DefaultTableModel model = (DefaultTableModel) tblEmployees.getModel();
       Employee selectedEmp = (Employee)model.getValueAt(selectedRowIndex, 0);
       
       userPic.setIcon(new ImageIcon(new ImageIcon(selectedEmp.getPhoto()).getImage().getScaledInstance(130,106, Image.SCALE_DEFAULT)));
       jTxtName.setText(selectedEmp.getName());
       jTxtEmpID.setText(selectedEmp.getEmpId().toString());
       jTxtStartDate.setText(selectedEmp.getStartDate());
       jTxtLevel.setText(selectedEmp.getLevel());
       jTxtAge.setText(selectedEmp.getAge().toString());
       jTxtTeamInfo1.setText(selectedEmp.getTeamInfo());
       jTxtGender.setText(selectedEmp.getGender());
       jTxtPositionTitle1.setText(selectedEmp.getPositionTitle());
       jTxtCellPhoneNum.setText(selectedEmp.getCellPhoneNumber().toString());
       jTxtEmail.setText(selectedEmp.getEmailAddress());
    }//GEN-LAST:event_jBtnViewActionPerformed

    private void jTxtSearchNameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTxtSearchNameKeyReleased
        String name = jTxtSearchName.getText();
        search(name);
    }//GEN-LAST:event_jTxtSearchNameKeyReleased

    private void jTxtSearchNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtSearchNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtSearchNameActionPerformed

    private void jTxtSearchIdKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTxtSearchIdKeyReleased
        String id = jTxtSearchId.getText();
        search(id);
    }//GEN-LAST:event_jTxtSearchIdKeyReleased

    private void jBtnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnUpdateActionPerformed
        int selectedRowIndex = tblEmployees.getSelectedRow();
       if(selectedRowIndex<0){
           JOptionPane.showMessageDialog(this, "Please select a row to update");
           return;
       };
        DefaultTableModel model = (DefaultTableModel) tblEmployees.getModel();
        Employee selectedEmp = (Employee)model.getValueAt(selectedRowIndex, 0);
        
        String name = jTxtName.getText();
        int empId = Integer.parseInt(jTxtEmpID.getText());
        int age = Integer.parseInt(jTxtAge.getText());
        String gender = jTxtGender.getText();
        String startDate = jTxtStartDate.getText();
        String level = jTxtLevel.getText();
        String teamInfo = jTxtTeamInfo1.getText();
        String title = jTxtPositionTitle1.getText();
        String cellPhoneNumber = jTxtCellPhoneNum.getText();
        String email = jTxtEmail.getText();
        
        
        
        
        Pattern pattern = Pattern.compile("\\d{10}");
        Matcher matcher = pattern.matcher(cellPhoneNumber);
        
        String emailFormate ="^[a-zA-Z0-9_!#$%&'*+/=?`{|}~^-]+(?:\\."  
                + "[a-zA-Z0-9_!#$%&'*+/=?`{|}~^-]+)*@[a-zA-Z0-9-]+(?:\\.[a-zA-Z0-9-]+)*$"; 
        Pattern p = Pattern.compile(emailFormate); 
        
        
        
       
        if(!matcher.matches())
        {
            JOptionPane.showMessageDialog(null, "Please enter a 10 digit cell phone number");
            jTxtCellPhoneNum.setText(null);
                
        }
        else if(!p.matcher(email).matches()){
            {
                JOptionPane.showMessageDialog(null, "Please enter a valid email id");
                jTxtEmail.setText(null);
                
            }
        }
        else
        {
            
         selectedEmp.setName(name);
        selectedEmp.setEmpId(empId);
        selectedEmp.setAge(age);
        selectedEmp.setStartDate(startDate);
        selectedEmp.setGender(gender);
        selectedEmp.setLevel(level);
        selectedEmp.setTeamInfo(teamInfo);
        selectedEmp.setPositionTitle(title);
        selectedEmp.setCellPhoneNumber(cellPhoneNumber);
        selectedEmp.setEmailAddress(email);
        
        populateTable();
        
            JOptionPane.showMessageDialog(this, "Information is saved");
                jTxtName.setText(null);
       jTxtEmpID.setText(null);
       jTxtStartDate.setText(null);
       jTxtLevel.setText(null);
       jTxtAge.setText(null);
       jTxtTeamInfo1.setText(null);
       jTxtGender.setText(null);
       jTxtPositionTitle1.setText(null);
       jTxtCellPhoneNum.setText(null);
       jTxtEmail.setText(null);
       userPic.setIcon(null);
            
        }
        
        
        
        
        
        
       
        
       
        
    }//GEN-LAST:event_jBtnUpdateActionPerformed

    private void tblEmployeesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblEmployeesMouseClicked
        
    }//GEN-LAST:event_tblEmployeesMouseClicked

    private void jTxtCellPhoneNumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtCellPhoneNumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtCellPhoneNumActionPerformed

    private void jTxtEmpIDKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTxtEmpIDKeyPressed
        char ch = evt.getKeyChar();
                if(Character.isDigit(ch)){
                }
                else{
                    JOptionPane.showMessageDialog(null, "Only numbers are allowed!");
                    jTxtEmpID.setText(null);
                }
    }//GEN-LAST:event_jTxtEmpIDKeyPressed

    private void jTxtAgeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTxtAgeKeyPressed
               char ch = evt.getKeyChar();
                if(Character.isDigit(ch)){
                }
                else {
                    JOptionPane.showMessageDialog(null, "Only numbers are allowed!");
                    jTxtAge.setText(null);
                }
    }//GEN-LAST:event_jTxtAgeKeyPressed

    private void jTxtCellPhoneNumKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTxtCellPhoneNumKeyPressed
            char ch = evt.getKeyChar();

                if(Character.isDigit(ch)){
                }
                else{
                    JOptionPane.showMessageDialog(null, "Only numbers are allowed!");
                    jTxtCellPhoneNum.setText(null);
                }
    }//GEN-LAST:event_jTxtCellPhoneNumKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnDelete;
    private javax.swing.JButton jBtnUpdate;
    private javax.swing.JButton jBtnView;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTxtAge;
    private javax.swing.JTextField jTxtCellPhoneNum;
    private javax.swing.JTextField jTxtEmail;
    private javax.swing.JTextField jTxtEmpID;
    private javax.swing.JTextField jTxtGender;
    private javax.swing.JTextField jTxtLevel;
    private javax.swing.JTextField jTxtName;
    private javax.swing.JTextField jTxtPositionTitle1;
    private javax.swing.JTextField jTxtSearchId;
    private javax.swing.JTextField jTxtSearchName;
    private javax.swing.JTextField jTxtStartDate;
    private javax.swing.JTextField jTxtTeamInfo1;
    private javax.swing.JTable tblEmployees;
    private javax.swing.JLabel userPic;
    // End of variables declaration//GEN-END:variables

    private void populateTable() {
        DefaultTableModel model = (DefaultTableModel) tblEmployees.getModel();
        model.setRowCount(0);
        for(Employee e: empHistory.getEmpHistory()){
            Object[] row = new Object[4];
            row[0] = e;
            row[1] = e.getEmpId();
            row[2] = e.getPositionTitle();
            row[3] = e.getLevel();
            model.addRow(row);
        }
    }
    
    public void search(String search){
         DefaultTableModel model = (DefaultTableModel) tblEmployees.getModel();
         TableRowSorter<DefaultTableModel> trs = new TableRowSorter(model);
         tblEmployees.setRowSorter(trs);
         trs.setRowFilter(RowFilter.regexFilter(search));
    }
}
